eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: pcc-zuul
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: pcc-api