eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: pcc-api
  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:8888/
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
