spring:
  application:
    name: pcc-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/FullDeveloper/cloudConfig/
          search-paths: respo
          username:
          password:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8888
